version: "3.9"

services:
  frontend:
    build: .
    container_name: frontend
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 8080:8080
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev