version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 8080:8080
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev

  backend:
    build: ./backend/backend
    container_name: backend
    volumes:
      - ./backend/backend:/app
    ports:
      - 5000:5000