version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 8080:8080
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev
    depends_on:
      - "backend"
      - "database"

  backend:
    build: ./backend/backend
    container_name: backend
    volumes:
      - ./backend/backend:/app
    ports:
      - 5000:5000
    depends_on:
      - "database"

  database:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=docker_test_db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data